version: '2'
services:
    zookeeper:
        image: zookeeper
        restart: always

    nimbus:
        image: storm
        command: storm nimbus
        depends_on:
            - zookeeper
        links:
            - zookeeper
        restart: always
        ports:
            - 6627:6627

    supervisor:
        image: storm
        command: storm supervisor
        depends_on:
            - nimbus
            - zookeeper
        links:
            - nimbus
            - zookeeper
        restart: always

    ui:
        image: storm
        command: storm ui
        depends_on:
            - nimbus
            - zookeeper
            - supervisor
        links:
            - nimbus
            - zookeeper
        restart: always
        ports:
            - 8080:8080

    kafka:
        image: wurstmeister/kafka
        ports:
            - 9092:9092
        depends_on:
            - zookeeper
        restart: always
        environment:
            KAFKA_ADVERTISED_HOST_NAME: 172.16.11.156
            KAFKA_CREATE_TOPICS: "tests:1:1"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        volumes:
              - /var/run/docker.sock:/var/run/docker.sock

    cassandra:
        image: cassandra
        restart: always
        ports:
            - 9042:9042
            - 9160:9160

    myweb-storm:
        image: storm
        command: storm jar /topology.jar storm.Topology
        depends_on:
            - nimbus
            - zookeeper
            - supervisor
            - kafka
            - cassandra
        links:
            - nimbus
            - zookeeper
            - supervisor
            - kafka
            - cassandra
        volumes:
            - ./target/akka-kafka-storm-cassandra-assembly-0.0.1.jar:/topology.jar

    akka-kafka-storm-cassandra-api:
        build: .
        depends_on:
            - zookeeper
            - kafka
            - myweb-storm
            - cassandra
        links:
            - zookeeper
            - kafka
            - cassandra
        restart: always
        ports:
            - 8090:8090
            - 9090:9090
